### PR TITLE
Add 'dbt-cloud run cancel-all' command

### LINKED ISSUE #46: dbt-cloud run cancel-all
Add the ability to cancel all existing runs similar to `job delete-all`. 

Should build on top existing https://github.com/data-mie/dbt-cloud-cli#dbt-cloud-run-cancel

### PR DESCRIPTION
**Pull request by jeremyyeo**
## Description & motivation

Resolves #46 

## Checklist
- [ ] I have written unit tests for new features (e.g., a new command test case in [conftest.py](../tests/conftest.py))
- [ ] I have written integration tests for new features (e.g., a new step in the [CI workflow](workflows/ci.yml))
- [x] I have added descriptions to new commands and arguments
- [x] I have updated the README.md (if applicable)

### CODE REVIEW

**Comment by jeremyyeo** [comment]
@stumelius any thoughts on users currently having to explicitly specify the status:

```
dbt-cloud run cancel-all --status Running
dbt-cloud run cancel-all --status Queued
```

I think that should be fine yea? :)

**Comment by stumelius** [comment]
@jeremyyeo Awesome work! 💯 I tested the command locally and it works as expected. The `integration-tests` workflow works only for maintainers because the dbt Cloud API credentials are stored as Github Secrets which are only available for PRs created by maintainers :(

**Comment by stumelius** [comment]
The only thing missing is adding the command to README. Can you do that? :) I can add the integration test afterwards.

**Comment by jeremyyeo** [comment]
> @jeremyyeo Awesome work! 💯 I tested the command locally and it works as expected. The `integration-tests` workflow works only for maintainers because the dbt Cloud API credentials are stored as Github Secrets which are only available for PRs created by maintainers :(

Aha... so that was what Claus was talking about in Slack https://getdbt.slack.com/archives/CU4MRJ7QB/p1649036043428879?thread_ts=1649035837.497879&cid=CU4MRJ7QB

**Comment by jeremyyeo** [comment]
Btw, do you think we should compress all those json responses in `README.md`? Maybe one example response per command rather than have the same ones for each command and their options? Seems like it may be getting very long and perhaps becoming not very useful.

**Comment by stumelius** [comment]
> > @jeremyyeo Awesome work! 💯 I tested the command locally and it works as expected. The `integration-tests` workflow works only for maintainers because the dbt Cloud API credentials are stored as Github Secrets which are only available for PRs created by maintainers :(
> 
> Aha... so that was what Claus was talking about in Slack https://getdbt.slack.com/archives/CU4MRJ7QB/p1649036043428879?thread_ts=1649035837.497879&cid=CU4MRJ7QB

It looks like they had the same issue with the [dbt_date ](https://github.com/calogica/dbt-date) project. They solved it by switching to CircleCI. I'll consider doing the same. Thanks for bringing this to my attention!

**Comment by stumelius** [comment]
> Btw, do you think we should compress all those json responses in `README.md`? Maybe one example response per command rather than have the same ones for each command and their options? Seems like it may be getting very long and perhaps becoming not very useful.

Excellent suggestion! You're totally right, the README is already waaay too long. I'll compress the responses.

**Comment by stumelius** [comment]
@jeremyyeo All of this looks good so I'll merge this. Thanks again for your work ❤️

**Pull request merged**
